apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../workloads/open-webui
  - open-webui-eso.yaml

  - ../../../workloads/litellm
  - litellm-config.yaml
  - litellm-eso.yaml

patches:
  - path: open-webui-patch.yaml
  - path: litellm-patch.yaml
