apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm
data:
  config.yaml: |
    # =====================================================
    # LiteLLM Settings
    # =====================================================
    litellm_settings:
      drop_params: True
      cache: True
      cache_params:
        type: redis

    # =====================================================
    # Model List
    # =====================================================
    model_list:

    # -----AI Studio-----
      - model_name: aistudio:gemini-3-flash-preview
        litellm_params:
          model: gemini/gemini-3-flash-preview
          api_key: os.environ/AISTUDIO_FREE_KEY1
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-2.5-flash
        litellm_params:
          model: gemini/gemini-2.5-flash
          api_key: os.environ/AISTUDIO_FREE_KEY1
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-2.5-flash-lite
        litellm_params:
          model: gemini/gemini-2.5-flash-lite
          api_key: os.environ/AISTUDIO_FREE_KEY1
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-embedding-001
        litellm_params:
          model: gemini/gemini-embedding-001
          api_key: os.environ/AISTUDIO_FREE_KEY1
          input_cost_per_token: 0
          output_cost_per_token: 0
          model_info:
            mode: embedding


      - model_name: aistudio:gemini-3-flash-preview
        litellm_params:
          model: gemini/gemini-3-flash-preview
          api_key: os.environ/AISTUDIO_FREE_KEY2
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-2.5-flash
        litellm_params:
          model: gemini/gemini-2.5-flash
          api_key: os.environ/AISTUDIO_FREE_KEY2
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-2.5-flash-lite
        litellm_params:
          model: gemini/gemini-2.5-flash-lite
          api_key: os.environ/AISTUDIO_FREE_KEY2
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-embedding-001
        litellm_params:
          model: gemini/gemini-embedding-001
          api_key: os.environ/AISTUDIO_FREE_KEY2
          input_cost_per_token: 0
          output_cost_per_token: 0
          model_info:
            mode: embedding


      - model_name: aistudio:gemini-3-flash-preview
        litellm_params:
          model: gemini/gemini-3-flash-preview
          api_key: os.environ/AISTUDIO_FREE_KEY3
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-2.5-flash
        litellm_params:
          model: gemini/gemini-2.5-flash
          api_key: os.environ/AISTUDIO_FREE_KEY3
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-2.5-flash-lite
        litellm_params:
          model: gemini/gemini-2.5-flash-lite
          api_key: os.environ/AISTUDIO_FREE_KEY3
          input_cost_per_token: 0
          output_cost_per_token: 0

      - model_name: aistudio:gemini-embedding-001
        litellm_params:
          model: gemini/gemini-embedding-001
          api_key: os.environ/AISTUDIO_FREE_KEY3
          input_cost_per_token: 0
          output_cost_per_token: 0
          model_info:
            mode: embedding
