apiVersion: apps/v1
kind: Deployment
metadata:
  name: marzban-master
  namespace: marzban
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: marzban-master
  template:
    metadata:
      labels:
        app: marzban-master
    spec:
      containers:
        - name: marzban
          image: gozargah/marzban:latest
          ports:
            - containerPort: 8000
              name: web
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: marzban-data
              mountPath: /var/lib/marzban
      volumes:
        - name: marzban-data
          persistentVolumeClaim:
            claimName: marzban-data
