apiVersion: v1
kind: Service
metadata:
  name: marzban-service
  namespace: marzban
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "marzban"
spec:
  selector:
    app: marzban-master
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
