apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Production Core Components
  - ../../../../core/cert-manager
  - ../../../../core/cilium
  - ../../../../core/cloudnative-pg
  - ../../../../core/longhorn
  - ../../../../core/redis-operator
  - ../../../../core/tailscale-operator
