# clusters/production/sync/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - datastores.yaml
  - platform.yaml
  - system.yaml
  - workloads.yaml
