apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../system/cilium
  - secrets/cilium-secret.sops.yaml

  - ../../../../system/tailscale-operator
  - secrets/tailscale-secret.sops.yaml

  - ../../../../system/cloudflared
  - secrets/cloudflare-tunnel-secret.sops.yaml

  # - ../../../../system/cert-manager
  # - secrets/cloudflare-secret.sops.yaml

  - ../../../../system/cloudnative-pg
  - ../../../../system/redis-operator

patches:
  - path: patches/tailscale.yaml
    target:
      kind: HelmRelease
      name: tailscale
      namespace: tailscale
  - path: patches/cilium.yaml
    target:
      kind: HelmRelease
      name: cilium
      namespace: kube-system
