apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../datastores/postgres
  - postgres-users-secret.sops.yaml
  - postgres-databases.yaml
  - postgres-secret-store.yaml

  - ../../../datastores/redis

  - ../../../datastores/qdrant
  - qdrant-secret.sops.yaml

  - ../../../datastores/juicefs
  - juicefs-secret.sops.yaml
  - juicefs-eso.yaml
  - juicefs-sc.yaml
  - juicefs-dashboard-svc.yaml

patches:
  - path: postgres-users-patch.yaml
  - path: qdrant-patch.yaml
  - path: juicefs-patch.yaml
