apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../datastores/postgres
  - postgres-users-secret.sops.yaml
  - postgres-databases.yaml
  - postgres-secret-store.yaml

  - ../../../datastores/redis

patches:
  - path: postgres-users-patch.yaml
