apiVersion: apps/v1
kind: Deployment
metadata:
  name: sillytavern
  namespace: sillytavern
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sillytavern
  template:
    metadata:
      labels:
        app: sillytavern
    spec:
      containers:
        - name: sillytavern-container
          image: ghcr.io/sillytavern/sillytavern:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              memory: "3Gi"
          volumeMounts:
            - name: sillytavern-data
              mountPath: /home/node/app/config
              subPath: config
            - name: sillytavern-data
              mountPath: /home/node/app/data
              subPath: data
            - name: sillytavern-data
              mountPath: /home/node/app/plugins
              subPath: plugins
            - name: sillytavern-data
              mountPath: /home/node/app/public/scripts/extensions/third-party
              subPath: extensions
      volumes:
        - name: sillytavern-data
          persistentVolumeClaim:
            claimName: sillytavern-data
