apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sillytavern-ingress
  namespace: sillytavern
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - st.textverse.top
      secretName: sillytavern-tls
  rules:
    - host: st.textverse.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sillytavern-svc
                port:
                  number: 80
