apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "sillytavern"
  name: sillytavern-svc
  namespace: sillytavern
spec:
  selector:
    app: sillytavern
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000