apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ha
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"  # 明确标记为非默认
parameters:
  fsType: ext4
  numberOfReplicas: "3"  # 改为 3 副本，与默认的 2 副本区分
  staleReplicaTimeout: "2880"  # 48小时
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
