apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
  # Uncomment the services you want to deploy to Sandbox
  # - ../../../../services/postgres-clusters
  # - ../../../../services/redis-instance
