apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
  # Uncomment the apps you want to deploy to laboratory
  # - ../../../../apps/actual-budget
  # - ../../../../apps/open-webui
