apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../platform/coder
  - coder-eso.yaml
  - coder-auth.sops.yaml
  - coder-apps-ingress.yaml

patches:
  - path: coder-patch.yaml
