apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: []
  # - ../../../../datastores/garage
  # - ../../../../datastores/juicefs
  # - ../../../../datastores/longhorn # Not used, kept for reference
