apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../datastores/postgres
  - ../../../../datastores/redis

patches:
  - path: patches/postgres-patch.yaml
  - path: patches/redis-patch.yaml
