apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpi
  namespace: gpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpi
  template:
    metadata:
      labels:
        app: gpi
    spec:
      containers:
      - name: gpi
        image: ghcr.io/su-kaka/gcli2api:latest
        ports:
        - containerPort: 7861
        volumeMounts:
        - name: creds
          mountPath: /app/creds
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
      volumes:
      - name: creds
        persistentVolumeClaim:
          claimName: gpi-creds
