apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../platform/infisical
  - infisical-secret.sops.yaml
  - infisical-eso.yaml

patches:
  - path: infisical-patch.yaml
