apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../platform/victoria-logs

# (Get-Content dashboard.json -Raw) -replace 'UID', 'P4169E866C3094E38' | Set-Content dashboard.json
configMapGenerator:
  - name: victorialogs-dashboard
    namespace: monitoring
    files:
      - dashboards/vlogs-dashboard.json

generatorOptions:
  labels:
    grafana_dashboard: "1"
