---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgB7lPqm5tKrnkj6LPJq9R9KRBogqDkp39YpvKt6RWHwm5QPE34GdYEP/kshroyly27norlcqhEzTPGArrLhoh789pWHDxzvxF9w6H2lwJVnAiGgjo5J9msXQLor2FAIKXmfHM6lTPZ25W71QFbyKJlZZbHzfMwMyabigQurQU4HTCpRrAAPHyaGyTt5BiwsNMAI9fa2zY9jYCT40/x/di0YD5s058t+RivkCbM+C5gbaOVO4JZYbfGCzUAAEgTYz9LE85j/IIo0b4gKEMqocfZGjCfNb1ierd/ZFGzcDzV/3yemYGRqJFhwK5G0D1NkBrVsZipzrnjnULaNSTxMWQNmPDqlhffPxl81T9smjyKxoe3mrnPKfOVLV1co1oskcOtJkNjmjEmsgXTdtH0vP2s0+Ij2bZT0bwk1GgioIhe5XKY+kwz14L1tdsqwkZUMmUYvZHYLwVirNQGnXEkb7AlhxqNIshcpPoUTEZ07Lpc3swd7sN+MFAmtijm3Zmh3qfLRzSez6u+QlyItdIMD9C0AmOP0J8WvsR+cdN1wvPLPQIpDJ09kZl9kuetjJkxP5J60V0aPuaEBMvraaZR+xsncoym2gxUIyze4n0LBSZ1CVjvtIFF7Be5C/Mr+HdvKtNEwDfrtQZRQ6gJBh6EsGXV536/O7Vlkv2D4fhAnhO6wr+Fi7+PXwqk7OD0CAqadhyj7py1CPJtC/z2r7u7XtWo9pw==
    client_secret: AgAYad3/GVkjdtJz/hWkLX9l8YyFdvD4SS1fZ6V+IhRA2elHn738zPCeYXfUQotQMqrZuTFgQKM8E1eW/K8GGla+dKYpKkPOWaQtpoqT/LsU/yWaqVOiOccCy+T4D3kRR5Ul7eQYBoDhD/2NWyxtQqdAiZo/v38vV0focLHNizzqDv4vVNSSfJ105QwDvOCxV/Fx7OYD/Ai/Sdw2FA2ZB7xkR8gt31Ol9lCfuvucLRNCi4USaLsSWJhrg5hMeIRXYmDT0voJE88T1wFfugek8+bHr4MktE0LFwY8O8GJyA0hFe3z5vEcWdhqG83ZXxT0bGIzoNBeuAeBtEoxrDEju7zz3dtiiLghntHj8gEytqOO7yBqDtDg++x4iNwVXNwj0694ttB3ZBueHs/islY89pnYAWPd3cfHu9TnYl3wyrEMWn3zJdsVb9YNBZJs/gOPdn5209QNEwFshl1k04aenoLG7um/YG/vKyNW8LHoEYzVpiLqBBfNDGPKH8cG0RA8wKzjNZ5a5eQ/cx2KYBVAQrroIupSSgKN0YKs54SHyr915mAUpQrZx/jM9LpVYVt9cAG+f2RzmuNxcPXBg333/zaM3v7FPry1kvUQuBdSjnM7TS0VKOByv0H6tI8MK40UKtOnceVvBmlMKQ9Mr4pkPjVz3cH3Ksyvdzl/zxrOM7AMr3EPB6FArdZLNX2djbvp8KiNVrf4A/meJvgAql3pU8A4K+bkSVcgivkpXhEDOFwc73GiB0YaypOPGUKRppIBe0KBgegLBqY1DeSNvVMkems=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
    type: Opaque
