apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quartz
  namespace: quartz
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - simplelumine.com
      secretName: quartz-tls
  rules:
    - host: simplelumine.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quartz
                port:
                  number: 80
