apiVersion: v1
kind: Service
metadata:
  name: quartz
  namespace: quartz
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "quartz"
spec:
  selector:
    app: quartz
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
