apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../datastores/juicefs
  - juicefs-secret.sops.yaml
  - juicefs-eso.yaml
  - juicefs-sc.yaml
  - juicefs-dashboard-svc.yaml

patches:
  - path: juicefs-patch.yaml
