apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 核心基础设施组件的 FluxCD Kustomization CRDs
# 每个组件一个独立的 yaml 文件

resources:
  - portainer-agent.yaml
  - tailscale-operator.yaml
  # - cert-manager.yaml
  # - longhorn.yaml
