apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-app-config
  namespace: litellm
data:
  # --- 第一个文件 ---
  parent_config.yaml: |

    include:
      - ./vertexai_config.yaml

      - ./aistudio_config.yaml

      # - ./aistudio_paid_config.yaml

      # - ./databricks_config.yaml

      - ./oaipro_config.yaml

      - ./deepseek_config.yaml

      - ./azure_config.yaml

      - ./xai_config.yaml

      - ./third-party_config.yaml
      # - ./gemini_cli_config.yaml
      # - ./dashscope_config.yaml

      # - ./openrouter_config.yaml

      - ./aistudio_free_config.yaml

      # - ./aistudio_free_1_config.yaml
      # - ./aistudio_free_2_config.yaml
      # - ./aistudio_free_3_config.yaml

    litellm_settings:
      drop_params: True
      set_verbose: True
      cache: True
      cache_params:
        type: redis
        namespace: "litellm.cache"
        ttl: 300

    router_settings:
      routing_strategy: simple-shuffle
      num_retries: 3
      timeout: 300
      # model_group_alias: {"gemini-2.5-pro": "aistudio:gemini-2.5-pro", "claude-sonnet-4-20250514": "claude-sonnet-4-20250514","claude-3-5-haiku-20241022": "claude-sonnet-4-20250514-glm"}
      # fallbacks: [{"aistudio:gemini-2.5-pro": ["aistudio:gemini-2.5-pro:free"]}]

  vertexai_config.yaml: |

    model_list:
    # 2.0
      # - model_name: vertexai:gemini-1.5-pro-002
      #   litellm_params:
      #     model: vertex_ai/gemini-1.5-pro-002
      #     vertex_project: os.environ/
