apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../platform/vaultwarden
  - vaultwarden-eso.yaml
  - ingress.yaml
patches:
  - path: vaultwarden-patch.yaml
    target:
      kind: Deployment
      name: vaultwarden
